apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: metallb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speaker
  namespace: metallb-system
---
# Add other MetalLB installation resources here
